#!/usr/bin/env sh

set -e

sh /etc/scripts/fix-mount.sh

if [ -n "$PHP_PROFILER" ]; then
    if [ -f "/etc/php/conf.d/${PHP_PROFILER}.disabled" ]; then
        sudo mv "/etc/php/conf.d/${PHP_PROFILER}.disabled" "/etc/php/conf.d/${PHP_PROFILER}.ini"
        echo "Enabled PHP Profiler: $PHP_PROFILER"
    else
        echo "Warning: PHP Profiler '$PHP_PROFILER' configuration not found."
    fi
fi

if ! sudo ping -c 1 database > /dev/null 2>&1; then
    MY_CNF="$HOME/.my.cnf"
    if [ -f "$MY_CNF" ]; then
        sed -i 's/host\s*=\s*database/host = 127.0.0.1/g' "$MY_CNF"
    fi
fi

exec $@
